import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HarmonySetup } from "harmony-ai-editor";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}<HarmonySetup repositoryId="5ca20331-af85-4bd7-87db-6f28e10de917"/></body>
    </html>
  );
}
